# server configuration
server:
  # 端口
  port: 8000
  # https
  enableTLS: false
  readTimeout: 60
  writeTimeout: 60


# app configuration
app:
  # 应用名称
  name: go-blog
  # 应用版本
  version: v1.0.0
  # 运行模式： debug/release
  run-mode: release
  # 是否打印带有颜色的日志
  log-color-colsole: true
  # 数据库类型，暂时只有mysql，其他的需要自己支持开发
  db-type: mysql
  # 静态文件路径
  static-path: static/
  # 存储类型 local/qiniu/aliyun-oss/tencent-oss
  storage-type: local
  # 允许上传文件的大小 单位KB/MB/GB/，不允许出现小数 如0.5GB，因为浮点数会丢失精度 比如5.2MB，转换成可能会变成5.18MB
  upload-max-size: 2GB
  # 允许的文件扩展名，不支持复合扩展名
  upload-allow-exts:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .psd
    - .icon
    - .gif
    - .mp3
    - .wav
    - .mid
    - .flac
    - .mp4
    - .mov
    - .avi
    - .flv
    - .m4v
    - .rmvb
    - .zip
    - .rar
    - .tar
    - .gz
    - .bz2
    - .doc
    - .xlsx
    - .pdf
    - .ppt
    - .pptx
    - .xls
    - .word
    - .md
    - .html
    - .js
    - .css
    - .java
    - .class
    - .py
    - .go
    - .sh
    - .logs
    - .yaml
    - .yml
    - .ini
    - .xmind
    - .json
    - .txt
  # accessToken过期时间10分钟
  access-token-expire: 60*10
  # refreshToken过期时间 7天
  refresh-token-expire: 60*7*24

# 雪花算法初始化的参数
snowflake:
  work-id: 1
  data-center-id: 1

# zap logs configuration
zap:
  # logs level  default: info
  level: 'info'
  # 日志输出格式，可选： `json` 和 `console`
  format: 'console'
  # 日志文件目录
  director: 'logs'
  # 日志文件名称
  linkName: 'latest_log'
  # 显示行号
  showLine: true
  encodeLevel: 'LowercaseColorLevelEncoder'
  stacktraceKey: 'stacktrace'
  # 是否打印日志在控制台
  logInConsole: true
  # 滚动日志存储大小
  logMaxSize: 1000
  # 滚动日志存储周期
  logMaxAge: 30
  # 滚动日志文件备份
  logMaxBackups: 5

mysql:
  username: root # 数据库用户名
  password: ren123 # 数据库密码
  host: 127.0.0.1 # 数据库地址
  port: 3306 # 数据库端口
  db-name: go_blog # 数据库名称
  parse-time: True # 解析时间
  charset: utf8 # 字符集
  log-mode: info  # info/
  max-idle-conns: 10 # 连接池最大空闲连接
  max-open-ponns: 30 # 连接池最大连接数

smtp:
  # smtp邮件服务器的地址
  host:
  # smtp服务器端口
  port:
  # smtp服务器鉴权用户名
  username:
  # smtp服务器鉴权密码
  password:
  # 是否使用ssl
  isSSL:
  # 发送邮件的用户地址
  from:

jwt:
  # jwt的密钥
  secret:
  # jwt的过期时间
  expire: 7200000s
  # jwt的issuer
  issuer:

# 本地存储
local:
  path: static/uploads/

# 七牛云存储
qiniu:
  zone: zone
  bucket: ''
  img-path: ''
  use-https: true
  access-key: ''
  secret-key: ''
  domain: ''

# 阿里云oss存储
aliyun-oss:
  # 阿里云访问节点，服务器和oss再同一地域可以使用内网域名
  endpoint: ''
  # AK
  access-key-id: ''
  # AS
  access-key-secret: ''
  # bucket空间名称
  bucket-name: ''
  # 自定义域名或阿里云oss bucket域名
  bucket-url: ''
  http-timeout: 10
  # 阿里云oss读写超时时间
  read-write-timeout: 200
  # 是否开启crc校验，默认开启
  enable-crc: false
  # 是否允许覆盖同名文件 默认false表示允许覆盖 true表示不允许覆盖
  forbid-over-write: true

# 腾讯云oss
tencent-oss:
  bucket: ''
  region: ''
  secret-id: ''
  secret-key: ''
  base-url: ''
  base-prefix: ''
